### ISSUE TITLE
the running result in spike meet error.

### ISSUE THREAD

**Issue by chyyuu** [illustris/FreeRTOS-RISCV#1]
hi, illustris, 
Great work!
I compiled and installed the newest riscv-tools.
I can compile FreeRTOS-RISCV (32bit & 64bit) correctly.
But I can not run riscv-spike.elf in spike, it looks can load an run, but meet error.

$ riscv32-spike riscv-spike.elf 
riscv32-spike: ../fesvr/device.cc:44: void device_t::handle_identify(command_t): Assertion `addr % IDENTITY_SIZE == 0' failed.

 riscv64-spike riscv64-spike.elf 
: q
no output.

Can you give me any advice?
Thank you!

**Comment by illustris** [comment]
Which privspec are you using? This is 1.9

**Comment by chyyuu** [comment]
privspec 1.9.1， the newest.

**Comment by illustris** [comment]
The guys over at IITM's RISE labs have updated FreeRTOS to 1.9.1. I'll have that added to this repo in a day or two

**Comment by chyyuu** [comment]
hi, illustris, Thank you!
How about current status?
I didn't find the updated FreeRTOS to 1.9.1.

**Comment by illustris** [comment]
Hi, I'm sorry it took this long. the master branch works on priv-1.9.1
