### ISSUE TITLE
Need Info on Uart addition to FreeRtos RISCV port

### ISSUE THREAD

**Issue by ghost** [illustris/FreeRTOS-RISCV#11]
Hi,

I am looking for UART driver address location and related information. I do find options to configure UART at different location for luminarymicro. Is there something similar there for RISCV port ? 
Suppose I want to configure at adrress 0x11200. how to do it ?

**Comment by noureddine-as** [comment]
Hello,
This version of FreeRTOS has been developed for tethered RISC-V systems. It
works on Spike and Rocket Chip C-Emulator (check Rocket Chip repository, the process of testing and debugging is explained there) and uses special memory sections called ".tohost" and
".fromhost" to communicate. 

I don't see how you can work with real UART
using Spike. However, you can use Rocket-Chip for that, by adding a UART peripheral from
SiFive blocks repository. They have UART hardware blocks written in Chisel
+ drivers that you can use to build an emulator with UART.
Check these repositories
https://github.com/sifive/freedom-e-sdk/tree/master/bsp
https://github.com/sifive/sifive-blocks/tree/master/src/main/scala/devices/uart

I hope this can help.
Best regards.

**Comment by ghost** [comment]
Thanks for the response.
