### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by dpmjoshi** [illustris/FreeRTOS-RISCV#2]
Hi Harikrishnan,

Can you please add a readme file that can describe what changes you made in the port. 
looking forward to use FreeRTOS on spike simulator.

**Comment by illustris** [comment]
I have been meaning to make a writeup of that. Unfortunately, right now I'm too busy with midsem project work. It'll take me a bit of time to document the changes. Until then, running git diff between the first and last commit on the priv-1.9 branch should shed some light on the changes

**Comment by dpmjoshi** [comment]
No worries... git diff will do. carry on with your midsem project.
