### ISSUE TITLE
timer interrupt not firing 

### ISSUE THREAD

**Issue by soybean-hust** [illustris/FreeRTOS-RISCV#3]
Thanks this amazing port to spike.
But simple demo running just two tasks with printf and delay will not schedule correctly due to timer IRQ not firing as it should. 
Context_Restore force mstatus to 0x1800, mret will clear MIE.  
Temp fix is to remove csrs in ContextRestore, and only set mstatus to 1880 in Yield, right before ContextRestore. Not sure if this will have some side-effects.

**Comment by charismimi** [comment]
I also meet the some problem and I fix the first item of timer interrupt enable issue as well. but I still can't work scheduler correctly. It seems task context something wrong with it. What should I fix?

**Comment by illustris** [comment]
It seems to be working with the latest pull requests merged. I'm closing the issue, but if it doesn't work, please reopen.
