### ISSUE TITLE
Run-time access fault with default build

### ISSUE THREAD

**Issue by sherrbc1** [illustris/FreeRTOS-RISCV#5]
The binary does not build without modification because [this](https://github.com/illustris/FreeRTOS-RISCV/blob/master/Demo/riscv-spike/arch/configstring.h#L6) string is commented out. The build finishes properly if the string is uncommented, but [this](https://github.com/illustris/FreeRTOS-RISCV/blob/master/Source/portable/GCC/RISCV/port.c#L234) line ultimately causes a run-time access fault. 

The system will read memory from `CONFIG_STRING_ADDR+0x0c` and then attempt to dereference the result. When I ran it, this resulted in an attempt to dereference address `0x182b283`, which causes a run-time fault. It looks as if this code was introduced with abc678b947a82b5c4d129b3ab2dc3c0682c3725f.

What is the purpose of the configuration string and what should it be when running in spike?

**Comment by illustris** [comment]
Config string address is an obsolete method of getting the address of mtime/mtimecmp registers and other memory mapped IO. It will not work on newer versions of spike
