### ISSUE TITLE
FreeRTOS and lowRISC old spike simulation

### ISSUE THREAD

**Issue by noureddine-as** [illustris/FreeRTOS-RISCV#9]
Hello,
I'm trying to run FreeRTOS using Spike (lowRISC) but I get this problem:
**_On the right:_** The demo built with a (recent compiler from Rocket-Chip repo) and tested with (recent) spike
**_On the left  :_** The demo built with a lowRISC toolchain and tested with its 'old' spike --> got *** FAILED *** (tohost = 6)

Another case if i build the app with recent compiler and run it with old spike i get (tohost = 2)

![image](https://user-images.githubusercontent.com/23646052/37719559-9afd4f4a-2d25-11e8-8772-c60e4b72bf5c.png)

I guess this is due to ISA spec version incompatibility? How can I resolve this and run FreeRTOS under the lowRISC spike version?

Thank you very much for your efforts.

**Comment by illustris** [comment]
It might be because of ISA spec version incompatibility. The last version I personally verified was 1.9. Anything newer was contributed by others.

**Comment by noureddine-as** [comment]
Okey  @illustris thanks.
I'll use the latest version of Spike then. there is another problem is when i run it with multi-core -p<n> parameter, i'll put that on another issue to keep this clean.
Thank you very much.
